// src/data.js
const dishes = [
  {
    country: "シンガポール共和国",
    name: "チリクラブ",
    description: "カニをチリソースで炒めた名物料理",
    price: "320円",
    kcal: "31kcal",
    image: "images/chili_crab.webp",
  },
  {
    country: "タイ王国の料理",
    name: "ガイヤーン",
    description: "甘辛い特製ダレに絡めたジューシーなチキンとライムの爽やかな味わいが絶品！",
    price: "320円",
    kcal: "61kcal",
    image: "images/gai_yang.webp",
  },
  {
    country: "フィリピン共和国の料理",
    name: "チキンアドボ",
    description: "酸味と塩味が絶妙なフィリピンの国民食！",
    price: "320円",
    kcal: "87kcal",
    image: "images/chicken_adobo.webp",
  },
  {
    country: "ベトナム社会主義共和国の料理",
    name: "生春巻き",
    description: "エビや生野菜等をライスペーパーで巻いた料理",
    price: "320円",
    kcal: "48kcal",
    image: "images/fresh_spring_rolls.webp",
  },
  {
    country: "マレーシアの料理",
    name: "サンバルウダン",
    description: "ピリっと辛いマレーシア風エビチリ！",
    price: "320円",
    kcal: "98kcal",
    image: "images/sambal_udang.webp",
  },
  {
    country: "大韓民国の料理",
    name: "カンジャンセウ",
    description: "甘辛い醤油漬けが美味しい！！海老の醤油漬け！",
    price: "320円",
    kcal: "54kcal",
    image: "images/kanjang_saeu.webp",
  },
  {
    country: "オーストラリア連邦の料理",
    name: "ローストビーフ",
    description: "オーブンで焼き上げた！肉の旨みが楽しめる！",
    price: "320円",
    kcal: "49kcal",
    image: "images/roast_beef.webp",
  },
  {
    country: "ソロモン諸島の料理",
    name: "キャッサバ芋フライ",
    description: "ソロモンの主食作物であるキャッサバ芋を素揚げした料理！",
    price: "320円",
    kcal: "144kcal",
    image: "images/cassava_fries.webp",
  },
  {
    country: "バヌアツ共和国の料理",
    name: "スープミート",
    description: "肉団子と野菜を使った中華風料理！",
    price: "320円",
    kcal: "249kcal",
    image: "images/soup_meat.webp",
  },
  {
    country: "フィジー共和国の料理",
    name: "ココンダ",
    description: "白身魚と野菜、ココナッツクリームを使ったサラダ料理！！！",
    price: "320円",
    kcal: "109kcal",
    image: "images/kokonda.webp",
  },
  {
    country: "マーシャル諸島共和国の料理",
    name: "ポキ",
    description: "鮮魚とアボカド海鮮和え！！",
    price: "320円",
    kcal: "121kcal",
    image: "images/poke.webp",
  },
  {
    country: "ミクロネシア連邦の料理",
    name: "ミクロネシアンチキン",
    description: "醤油やレモンをかけたミクロネシアの名物料理！",
    price: "320円",
    kcal: "64kcal",
    image: "images/micronesian_chicken.webp",
  },
  {
    country: "オマーン国の料理",
    name: "ファラフェル",
    description: "ひよこ豆を使ったコロッケ！",
    price: "320円",
    kcal: "140kcal",
    image: "images/falafel.webp",
  },
  {
    country: "トルコ共和国の料理",
    name: "ケバブ",
    description: "スパイシーな味わいが魅力！",
    price: "320円",
    kcal: "80kcal",
    image: "images/kebab.webp",
  },
  {
    country: "英国（グレートブリテン及び北アイルランド連合王国）の料理",
    name: "サンデーロースト",
    description: "日曜日にいただく伝統的な食事！",
    price: "320円",
    kcal: "48kcal",
    image: "images/sunday_roast.webp",
  },
  {
    country: "イタリア共和国の料理",
    name: "タリアータ",
    description: "バルサミコソースで味わうイタリア定番料理！",
    price: "320円",
    kcal: "47kcal",
    image: "images/tagliata.webp",
  },
  {
    country: "オランダ王国の料理",
    name: "ハーリング",
    description: "ハーリングとはニシンを塩漬け、発酵させたオランダ伝統の魚料理。",
    price: "320円",
    kcal: "59kcal",
    image: "images/herring.webp",
  },
  {
    country: "クロアチア共和国の料理",
    name: "タコのサラダ",
    description: "タコのスライスを使ったクロアチア定番前菜！",
    price: "320円",
    kcal: "50kcal",
    image: "images/octopus_salad.webp",
  },
  {
    country: "コソボ共和国の料理",
    name: "チョフテ",
    description: "チョフテとは、ひき肉にスパイスやハーブを入れて焼いたもの！",
    price: "320円",
    kcal: "103kcal",
    image: "images/qofte.webp",
  },
  {
    country: "サンマリノ共和国の料理",
    name: "ピアディーナ",
    description: "野菜や生ハムを挟んだトルティーヤ！",
    price: "320円",
    kcal: "105kcal",
    image: "images/piadina.webp",
  },
  {
    country: "スイス連邦の料理",
    name: "マラコフ",
    description: "チーズに衣をつけて揚げたもので、ジュネーブの隣のヴォー州の名物料理。",
    price: "320円",
    kcal: "244kcal",
    image: "images/malakoff.webp",
  },
  {
    country: "スウェーデン王国の料理",
    name: "ミートボール",
    description: "甘酸っぱいジャムを添えたスウェーデン風ミートボール！",
    price: "320円",
    kcal: "197kcal",
    image: "images/swedish_meatballs.webp",
  },
  {
    country: "スペイン王国の料理",
    name: "ハモンセラーノ",
    description: "世界三大生ハム！スペイン産生ハム！",
    price: "320円",
    kcal: "31kcal",
    image: "images/jamon_serrano.webp",
  },
  {
    country: "スロバキア共和国の料理",
    name: "カリフラワーナゲット",
    description: "チーズソースでいただくスロバキア定番料理！",
    price: "320円",
    kcal: "173kcal",
    image: "images/cauliflower_nuggets.webp",
  },
  {
    country: "デンマーク王国の料理",
    name: "スモーブロー",
    description: "チーズとサーモンのサンドイッチ！",
    price: "320円",
    kcal: "141kcal",
    image: "images/smorrebrod.webp",
  },
  {
    country: "ドイツ連邦共和国の料理",
    name: "カリーヴルスト",
    description: "ケチャップとカレー粉をまぶしたドイツ名物のB級グルメ！",
    price: "320円",
    kcal: "151kcal",
    image: "images/currywurst.webp",
  },
  {
    country: "ノルウェー王国の料理",
    name: "【ノルウェー産】サーモンカルパッチョ",
    description: "さっぱりソースでサーモンを美味しく！",
    price: "320円",
    kcal: "67kcal",
    image: "images/salmon_carpaccio.webp",
  },
  {
    country: "ハンガリーの料理",
    name: "鴨のロースト トリュフソース",
    description: "キャベツマリネを添えた旨みあふれる鴨のロースト！",
    price: "320円",
    kcal: "102kcal",
    image: "images/roast_duck.webp",
  },
  {
    country: "アイルランドの料理",
    name: "ボクスティ",
    description: "じゃがいもを使った伝統的なパンケーキ！",
    price: "320円",
    kcal: "62kcal",
    image: "images/boxty.webp",
  },
  {
    country: "アンゴラ共和国の料理",
    name: "チキンムアンバ",
    description: "ピーナッツソースをチキンにかけたアンゴラ伝統料理！",
    price: "320円",
    kcal: "136kcal",
    image: "images/chicken_muamba.webp",
  },
  {
    country: "エジプト・アラブ共和国の料理",
    name: "ダウードバシャ",
    description: "トマトカレーソースをかけて人気の料理を再現！",
    price: "320円",
    kcal: "194kcal",
    image: "images/dawood_basha.webp",
  },
  {
    country: "カメルーン共和国の料理",
    name: "マケロ",
    description: "アフリカ料理の特徴の塩、とうがらし、にんにくで味付けしている。",
    price: "320円",
    kcal: "109kcal",
    image: "images/makero.webp",
  },
  {
    country: "トーゴ共和国の料理",
    name: "アジデジ",
    description: "ピーナッツソースで絡めた鶏肉料理！",
    price: "320円",
    kcal: "135kcal",
    image: "images/ajideji.webp",
  },
  {
    country: "アメリカ合衆国の料理",
    name: "ハンバーガー",
    description: "日本でもおなじみのアメリカ発祥料理！",
    price: "320円",
    kcal: "275kcal",
    image: "images/hamburger.webp",
  },
  {
    country: "中央アフリカ共和国の料理",
    name: "フライドティラピア",
    description: "中央アフリカで定番の魚、ティラピアの素揚げ！",
    price: "320円",
    kcal: "54kcal",
    image: "images/fried_tilapia.webp",
  },
  {
    country: "キューバ共和国の料理",
    name: "ロパビエハ",
    description: "赤身肉を煮込んだキューバの伝統料理！",
    price: "320円",
    kcal: "54kcal",
    image: "images/ropa_vieja.webp",
  },
  {
    country: "コロンビア共和国の料理",
    name: "パパクリオージャ オガオソース",
    description: "トマトのサルサをかけたポテトフライ！",
    price: "320円",
    kcal: "79kcal",
    image: "images/papa_criolla.webp",
  },
  {
    country: "チリ共和国の料理",
    name: "エリソス",
    description: "エリソスはスペイン語でウニの意味。ウニの濃厚な味わい！チリの海の幸！",
    price: "320円",
    kcal: "25kcal",
    image: "images/erizos.webp",
  },
  {
    country: "ドミニカ共和国の料理",
    name: "ペスカド・コン・ココ",
    description: "白身魚の唐揚げココナッツソースがけ！",
    price: "320円",
    kcal: "69kcal",
    image: "images/pescado_con_coco.webp",
  },
  {
    country: "トリニダード・トバゴ共和国の料理",
    name: "ダブルス",
    description: "カレー風味のソースがかかったスナック感覚の国民食！！",
    price: "320円",
    kcal: "155kcal",
    image: "images/doubles.webp",
  },
  {
    country: "パナマ共和国の料理",
    name: "エンサラダデフェリア",
    description: "ビーツを使用したピンク色が珍しいパナマのポテサラ！",
    price: "320円",
    kcal: "75kcal",
    image: "images/ensalada_de_feria.webp",
  },
  {
    country: "ベリーズの料理",
    name: "ハバネロチキン",
    description: "ハバネロソースの旨辛さがやみつきに！",
    price: "320円",
    kcal: "54kcal",
    image: "images/habanero_chicken.webp",
  },
  {
    country: "ペルー共和国の料理",
    name: "セビーチェ",
    description: "新鮮な魚介を使ったぺルーのマリネ！",
    price: "320円",
    kcal: "64kcal",
    image: "images/ceviche.webp",
  },
  {
    country: "ボリビア多民族国の料理",
    name: "ピカンテデポジョ",
    description: "トマトチリソースをかけたスパイシーなチキン！",
    price: "320円",
    kcal: "75kcal",
    image: "images/picante_de_pollo.webp",
  },
  {
    country: "ホンジュラス共和国の料理",
    name: "カルネアサード",
    description: "トマトやオニオンのマリネと一緒に楽しむ肉料理！！",
    price: "320円",
    kcal: "53kcal",
    image: "images/carne_asada.webp",
  },
  {
    country: "パラグアイ共和国の料理",
    name: "ポジョ・アサード",
    description: "柔らかいジューシーチキンに酸味の効いたピリ辛特製ソースが旨さを引き立てる！",
    price: "320円",
    kcal: "69kcal",
    image: "images/pollo_asado.webp",
  },
  {
    country: "リトアニア共和国の料理",
    name: "シャルティバルシチャイ",
    description: "ビーツの甘味と酸味でさっぱり爽やかな伝統の冷製スープ！",
    price: "320円",
    kcal: "172kcal",
    image: "images/saltibarsciai.webp",
  },
  {
    country: "インドネシア共和国の料理",
    name: "コラックラブ",
    description: "ココナッツクリームとかぼちゃのインドネシアのデザート！",
    price: "320円",
    kcal: "150kcal",
    image: "images/kolak_labu.webp",
  },
  {
    country: "スリランカ民主社会主義共和国の料理",
    name: "キリパニ ※はちみつ使用",
    description: "スリランカで朝食として食されるヨーグルト料理！",
    price: "320円",
    kcal: "73kcal",
    image: "images/kiri_pani.webp",
  },
  {
    country: "バングラデシュ人民共和国の料理",
    name: "ミスティ",
    description: "「ミスティ＝甘いお菓子」甘いシロップをかけたドーナツ！",
    price: "320円",
    kcal: "386kcal",
    image: "images/mishti.webp",
  },
  {
    country: "中華人民共和国の料理",
    name: "月餅 ※はちみつ使用",
    description: "円形で表面に美しい模様が描かれている伝統的なお菓子",
    price: "320円",
    kcal: "225kcal",
    image: "images/mooncake.webp",
  },
  {
    country: "東ティモール民主共和国の料理",
    name: "エッグタルト",
    description: "ペイストリー生地の器に玉子とカスタードをのせて焼いたタルト！",
    price: "320円",
    kcal: "176kcal",
    image: "images/egg_tart.webp",
  },
  {
    country: "トンガ王国の料理",
    name: "ケケ",
    description: "丸く揚げた素朴な味のドーナツ！",
    price: "320円",
    kcal: "363kcal",
    image: "images/keke.webp",
  },
  {
    country: "パラオ共和国の料理",
    name: "アホ",
    description: "ココナッツと餅で作る甘い南国風おしるこ！",
    price: "320円",
    kcal: "144kcal",
    image: "images/aho.webp",
  },
  {
    country: "アラブ首長国連邦の料理",
    name: "パパロティ",
    description: "コーヒーソースがかかった中ふわ外カリの焼き菓子！",
    price: "320円",
    kcal: "172kcal",
    image: "images/paparoti.webp",
  },
  {
    country: "イエメン共和国の料理",
    name: "バナナブレッドプリン ※はちみつ使用",
    description: "バナナとはちみつを使ったふわふわプリン！",
    price: "320円",
    kcal: "120kcal",
    image: "images/banana_bread_pudding.webp",
  },
  {
    country: "イスラエルの料理",
    name: "マラビ",
    description: "ローズの風味が爽やかな伝統的デザート！",
    price: "320円",
    kcal: "94kcal",
    image: "images/malabi.webp",
  },
  {
    country: "カタール国の料理",
    name: "ルカイマット",
    description: "中はしっとり、外はカリ！カタールの伝統料理！",
    price: "320円",
    kcal: "380kcal",
    image: "images/luqaimat.webp",
  },
  {
    country: "サウジアラビア王国の料理",
    name: "ウムアリ",
    description: "ミルククリーム・フルーツの層を重ねた伝統的なデザート！",
    price: "320円",
    kcal: "121kcal",
    image: "images/umm_ali.webp",
  },
  {
    country: "フランス共和国の料理",
    name: "カヌレ",
    description: "優しい甘さの伝統的焼き菓子！",
    price: "320円",
    kcal: "174kcal",
    image: "images/canele.webp",
  },
  {
    country: "ベルギー王国の料理",
    name: "ベルギーワッフル ※はちみつ使用",
    description: "甘いチョコソースとサクサク食感が美味しい！",
    price: "320円",
    kcal: "141kcal",
    image: "images/belgian_waffle.webp",
  },
  {
    country: "ルーマニアの料理",
    name: "パパナシ",
    description: "サワークリームとジャムのルーマニア版ドーナツ！",
    price: "320円",
    kcal: "367kcal",
    image: "images/papanasi.webp",
  },
  {
    country: "エチオピア連邦民主共和国の料理",
    name: "コーヒータルト",
    description: "コクがあってフルーティーなコーヒーを使ったタルト！",
    price: "320円",
    kcal: "219kcal",
    image: "images/coffee_tart.webp",
  },
  {
    country: "ガンビア共和国の料理",
    name: "チャキリ",
    description: "様々なドライフルーツと味わうヨーグルト！",
    price: "320円",
    kcal: "117kcal",
    image: "images/chakery.webp",
  },
  {
    country: "ケニア共和国の料理",
    name: "コーヒーゼリー",
    description: "苦味とコクのバランスを活かしたコーヒーゼリー！",
    price: "320円",
    kcal: "90kcal",
    image: "images/coffee_jelly.webp",
  },
  {
    country: "マダガスカル共和国の料理",
    name: "マダガスカルバニラ パンケーキ",
    description: "マイルドな甘い香りのバニラカスタードを楽しむパンケーキ！",
    price: "320円",
    kcal: "134kcal",
    image: "images/vanilla_pancake.webp",
  },
  {
    country: "ウルグアイ東方共和国の料理",
    name: "アルファフォーレス",
    description: "クッキーでキャラメルクリームを挟んだクッキー菓子！",
    price: "320円",
    kcal: "166kcal",
    image: "images/alfajores.webp",
  },
  {
    country: "カナダの料理",
    name: "メープルパンケーキ",
    description: "甘くて美味しいコクのあるシロップ！！",
    price: "320円",
    kcal: "80kcal",
    image: "images/maple_pancake.webp",
  },
  {
    country: "グアテマラ共和国の料理",
    name: "グアテマラコーヒーゼリー",
    description: "コーヒーの酸味とすっきりと爽やかな後味が絶品！",
    price: "320円",
    kcal: "104kcal",
    image: "images/guatemala_coffee_jelly.webp",
  },
  {
    country: "ブラジル連邦共和国の料理",
    name: "ポンデケージョ",
    description: "チーズ味のクセになりそうなモチモチ食感！",
    price: "320円",
    kcal: "127kcal",
    image: "images/pao_de_queijo.webp",
  }
];

export default dishes;